export default [
  {
    name: 'Aruba',
    value: 'Aruba',
    flag: '\ud83c\udde6\ud83c\uddfc',
    countryCode: 'AW',
  },
  {
    name: 'Afghanistan',
    value: 'Afghanistan',
    flag: '\ud83c\udde6\ud83c\uddeb',
    countryCode: 'AF',
  },
  {
    name: 'Angola',
    value: 'Angola',
    flag: '\ud83c\udde6\ud83c\uddf4',
    countryCode: 'AO',
  },
  {
    name: 'Anguilla',
    value: 'Anguilla',
    flag: '\ud83c\udde6\ud83c\uddee',
    countryCode: 'AI',
  },
  {
    name: '\u00c5land Islands',
    value: '\u00c5land Islands',
    flag: '\ud83c\udde6\ud83c\uddfd',
    countryCode: 'AX',
  },
  {
    name: 'Albania',
    value: 'Albania',
    flag: '\ud83c\udde6\ud83c\uddf1',
    countryCode: 'AL',
  },
  {
    name: 'Andorra',
    value: 'Andorra',
    flag: '\ud83c\udde6\ud83c\udde9',
    countryCode: 'AD',
  },
  {
    name: 'United Arab Emirates',
    value: 'United Arab Emirates',
    flag: '\ud83c\udde6\ud83c\uddea',
    countryCode: 'AE',
  },
  {
    name: 'Argentina',
    value: 'Argentina',
    flag: '\ud83c\udde6\ud83c\uddf7',
    countryCode: 'AR',
  },
  {
    name: 'Armenia',
    value: 'Armenia',
    flag: '\ud83c\udde6\ud83c\uddf2',
    countryCode: 'AM',
  },
  {
    name: 'American Samoa',
    value: 'American Samoa',
    flag: '\ud83c\udde6\ud83c\uddf8',
    countryCode: 'AS',
  },
  {
    name: 'Antarctica',
    value: 'Antarctica',
    flag: '\ud83c\udde6\ud83c\uddf6',
    countryCode: 'AQ',
  },
  {
    name: 'French Southern Territories',
    value: 'French Southern Territories',
    flag: '\ud83c\uddf9\ud83c\uddeb',
    countryCode: 'TF',
  },
  {
    name: 'Antigua and Barbuda',
    value: 'Antigua and Barbuda',
    flag: '\ud83c\udde6\ud83c\uddec',
    countryCode: 'AG',
  },
  {
    name: 'Australia',
    value: 'Australia',
    flag: '\ud83c\udde6\ud83c\uddfa',
    countryCode: 'AU',
  },
  {
    name: 'Austria',
    value: 'Austria',
    flag: '\ud83c\udde6\ud83c\uddf9',
    countryCode: 'AT',
  },
  {
    name: 'Azerbaijan',
    value: 'Azerbaijan',
    flag: '\ud83c\udde6\ud83c\uddff',
    countryCode: 'AZ',
  },
  {
    name: 'Burundi',
    value: 'Burundi',
    flag: '\ud83c\udde7\ud83c\uddee',
    countryCode: 'BI',
  },
  {
    name: 'Belgium',
    value: 'Belgium',
    flag: '\ud83c\udde7\ud83c\uddea',
    countryCode: 'BE',
  },
  {
    name: 'Benin',
    value: 'Benin',
    flag: '\ud83c\udde7\ud83c\uddef',
    countryCode: 'BJ',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    value: 'Bonaire, Sint Eustatius and Saba',
    flag: '\ud83c\udde7\ud83c\uddf6',
    countryCode: 'BQ',
  },
  {
    name: 'Burkina Faso',
    value: 'Burkina Faso',
    flag: '\ud83c\udde7\ud83c\uddeb',
    countryCode: 'BF',
  },
  {
    name: 'Bangladesh',
    value: 'Bangladesh',
    flag: '\ud83c\udde7\ud83c\udde9',
    countryCode: 'BD',
  },
  {
    name: 'Bulgaria',
    value: 'Bulgaria',
    flag: '\ud83c\udde7\ud83c\uddec',
    countryCode: 'BG',
  },
  {
    name: 'Bahrain',
    value: 'Bahrain',
    flag: '\ud83c\udde7\ud83c\udded',
    countryCode: 'BH',
  },
  {
    name: 'Bahamas',
    value: 'Bahamas',
    flag: '\ud83c\udde7\ud83c\uddf8',
    countryCode: 'BS',
  },
  {
    name: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
    flag: '\ud83c\udde7\ud83c\udde6',
    countryCode: 'BA',
  },
  {
    name: 'Saint Barth\u00e9lemy',
    value: 'Saint Barth\u00e9lemy',
    flag: '\ud83c\udde7\ud83c\uddf1',
    countryCode: 'BL',
  },
  {
    name: 'Belarus',
    value: 'Belarus',
    flag: '\ud83c\udde7\ud83c\uddfe',
    countryCode: 'BY',
  },
  {
    name: 'Belize',
    value: 'Belize',
    flag: '\ud83c\udde7\ud83c\uddff',
    countryCode: 'BZ',
  },
  {
    name: 'Bermuda',
    value: 'Bermuda',
    flag: '\ud83c\udde7\ud83c\uddf2',
    countryCode: 'BM',
  },
  {
    name: 'Bolivia, Plurinational State of',
    value: 'Bolivia, Plurinational State of',
    flag: '\ud83c\udde7\ud83c\uddf4',
    countryCode: 'BO',
  },
  {
    name: 'Brazil',
    value: 'Brazil',
    flag: '\ud83c\udde7\ud83c\uddf7',
    countryCode: 'BR',
  },
  {
    name: 'Barbados',
    value: 'Barbados',
    flag: '\ud83c\udde7\ud83c\udde7',
    countryCode: 'BB',
  },
  {
    name: 'Brunei Darussalam',
    value: 'Brunei Darussalam',
    flag: '\ud83c\udde7\ud83c\uddf3',
    countryCode: 'BN',
  },
  {
    name: 'Bhutan',
    value: 'Bhutan',
    flag: '\ud83c\udde7\ud83c\uddf9',
    countryCode: 'BT',
  },
  {
    name: 'Bouvet Island',
    value: 'Bouvet Island',
    flag: '\ud83c\udde7\ud83c\uddfb',
    countryCode: 'BV',
  },
  {
    name: 'Botswana',
    value: 'Botswana',
    flag: '\ud83c\udde7\ud83c\uddfc',
    countryCode: 'BW',
  },
  {
    name: 'Central African Republic',
    value: 'Central African Republic',
    flag: '\ud83c\udde8\ud83c\uddeb',
    countryCode: 'CF',
  },
  {
    name: 'Canada',
    value: 'Canada',
    flag: '\ud83c\udde8\ud83c\udde6',
    countryCode: 'CA',
  },
  {
    name: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
    flag: '\ud83c\udde8\ud83c\udde8',
    countryCode: 'CC',
  },
  {
    name: 'Switzerland',
    value: 'Switzerland',
    flag: '\ud83c\udde8\ud83c\udded',
    countryCode: 'CH',
  },
  {
    name: 'Chile',
    value: 'Chile',
    flag: '\ud83c\udde8\ud83c\uddf1',
    countryCode: 'CL',
  },
  {
    name: 'China',
    value: 'China',
    flag: '\ud83c\udde8\ud83c\uddf3',
    countryCode: 'CN',
  },
  {
    name: "C\u00f4te d'Ivoire",
    value: "C\u00f4te d'Ivoire",
    flag: '\ud83c\udde8\ud83c\uddee',
    countryCode: 'CI',
  },
  {
    name: 'Cameroon',
    value: 'Cameroon',
    flag: '\ud83c\udde8\ud83c\uddf2',
    countryCode: 'CM',
  },
  {
    name: 'Congo, The Democratic Republic of the',
    value: 'Congo, The Democratic Republic of the',
    flag: '\ud83c\udde8\ud83c\udde9',
    countryCode: 'CD',
  },
  {
    name: 'Congo',
    value: 'Congo',
    flag: '\ud83c\udde8\ud83c\uddec',
    countryCode: 'CG',
  },
  {
    name: 'Cook Islands',
    value: 'Cook Islands',
    flag: '\ud83c\udde8\ud83c\uddf0',
    countryCode: 'CK',
  },
  {
    name: 'Colombia',
    value: 'Colombia',
    flag: '\ud83c\udde8\ud83c\uddf4',
    countryCode: 'CO',
  },
  {
    name: 'Comoros',
    value: 'Comoros',
    flag: '\ud83c\uddf0\ud83c\uddf2',
    countryCode: 'KM',
  },
  {
    name: 'Cabo Verde',
    value: 'Cabo Verde',
    flag: '\ud83c\udde8\ud83c\uddfb',
    countryCode: 'CV',
  },
  {
    name: 'Costa Rica',
    value: 'Costa Rica',
    flag: '\ud83c\udde8\ud83c\uddf7',
    countryCode: 'CR',
  },
  {
    name: 'Cuba',
    value: 'Cuba',
    flag: '\ud83c\udde8\ud83c\uddfa',
    countryCode: 'CU',
  },
  {
    name: 'Cura\u00e7ao',
    value: 'Cura\u00e7ao',
    flag: '\ud83c\udde8\ud83c\uddfc',
    countryCode: 'CW',
  },
  {
    name: 'Christmas Island',
    value: 'Christmas Island',
    flag: '\ud83c\udde8\ud83c\uddfd',
    countryCode: 'CX',
  },
  {
    name: 'Cayman Islands',
    value: 'Cayman Islands',
    flag: '\ud83c\uddf0\ud83c\uddfe',
    countryCode: 'KY',
  },
  {
    name: 'Cyprus',
    value: 'Cyprus',
    flag: '\ud83c\udde8\ud83c\uddfe',
    countryCode: 'CY',
  },
  {
    name: 'Czechia',
    value: 'Czechia',
    flag: '\ud83c\udde8\ud83c\uddff',
    countryCode: 'CZ',
  },
  {
    name: 'Germany',
    value: 'Germany',
    flag: '\ud83c\udde9\ud83c\uddea',
    countryCode: 'DE',
  },
  {
    name: 'Djibouti',
    value: 'Djibouti',
    flag: '\ud83c\udde9\ud83c\uddef',
    countryCode: 'DJ',
  },
  {
    name: 'Dominica',
    value: 'Dominica',
    flag: '\ud83c\udde9\ud83c\uddf2',
    countryCode: 'DM',
  },
  {
    name: 'Denmark',
    value: 'Denmark',
    flag: '\ud83c\udde9\ud83c\uddf0',
    countryCode: 'DK',
  },
  {
    name: 'Dominican Republic',
    value: 'Dominican Republic',
    flag: '\ud83c\udde9\ud83c\uddf4',
    countryCode: 'DO',
  },
  {
    name: 'Algeria',
    value: 'Algeria',
    flag: '\ud83c\udde9\ud83c\uddff',
    countryCode: 'DZ',
  },
  {
    name: 'Ecuador',
    value: 'Ecuador',
    flag: '\ud83c\uddea\ud83c\udde8',
    countryCode: 'EC',
  },
  {
    name: 'Egypt',
    value: 'Egypt',
    flag: '\ud83c\uddea\ud83c\uddec',
    countryCode: 'EG',
  },
  {
    name: 'Eritrea',
    value: 'Eritrea',
    flag: '\ud83c\uddea\ud83c\uddf7',
    countryCode: 'ER',
  },
  {
    name: 'Western Sahara',
    value: 'Western Sahara',
    flag: '\ud83c\uddea\ud83c\udded',
    countryCode: 'EH',
  },
  {
    name: 'Spain',
    value: 'Spain',
    flag: '\ud83c\uddea\ud83c\uddf8',
    countryCode: 'ES',
  },
  {
    name: 'Estonia',
    value: 'Estonia',
    flag: '\ud83c\uddea\ud83c\uddea',
    countryCode: 'EE',
  },
  {
    name: 'Ethiopia',
    value: 'Ethiopia',
    flag: '\ud83c\uddea\ud83c\uddf9',
    countryCode: 'ET',
  },
  {
    name: 'Finland',
    value: 'Finland',
    flag: '\ud83c\uddeb\ud83c\uddee',
    countryCode: 'FI',
  },
  {
    name: 'Fiji',
    value: 'Fiji',
    flag: '\ud83c\uddeb\ud83c\uddef',
    countryCode: 'FJ',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
    flag: '\ud83c\uddeb\ud83c\uddf0',
    countryCode: 'FK',
  },
  {
    name: 'France',
    value: 'France',
    flag: '\ud83c\uddeb\ud83c\uddf7',
    countryCode: 'FR',
  },
  {
    name: 'Faroe Islands',
    value: 'Faroe Islands',
    flag: '\ud83c\uddeb\ud83c\uddf4',
    countryCode: 'FO',
  },
  {
    name: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
    flag: '\ud83c\uddeb\ud83c\uddf2',
    countryCode: 'FM',
  },
  {
    name: 'Gabon',
    value: 'Gabon',
    flag: '\ud83c\uddec\ud83c\udde6',
    countryCode: 'GA',
  },
  {
    name: 'United Kingdom',
    value: 'United Kingdom',
    flag: '\ud83c\uddec\ud83c\udde7',
    countryCode: 'GB',
  },
  {
    name: 'Georgia',
    value: 'Georgia',
    flag: '\ud83c\uddec\ud83c\uddea',
    countryCode: 'GE',
  },
  {
    name: 'Guernsey',
    value: 'Guernsey',
    flag: '\ud83c\uddec\ud83c\uddec',
    countryCode: 'GG',
  },
  {
    name: 'Ghana',
    value: 'Ghana',
    flag: '\ud83c\uddec\ud83c\udded',
    countryCode: 'GH',
  },
  {
    name: 'Gibraltar',
    value: 'Gibraltar',
    flag: '\ud83c\uddec\ud83c\uddee',
    countryCode: 'GI',
  },
  {
    name: 'Guinea',
    value: 'Guinea',
    flag: '\ud83c\uddec\ud83c\uddf3',
    countryCode: 'GN',
  },
  {
    name: 'Guadeloupe',
    value: 'Guadeloupe',
    flag: '\ud83c\uddec\ud83c\uddf5',
    countryCode: 'GP',
  },
  {
    name: 'Gambia',
    value: 'Gambia',
    flag: '\ud83c\uddec\ud83c\uddf2',
    countryCode: 'GM',
  },
  {
    name: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
    flag: '\ud83c\uddec\ud83c\uddfc',
    countryCode: 'GW',
  },
  {
    name: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
    flag: '\ud83c\uddec\ud83c\uddf6',
    countryCode: 'GQ',
  },
  {
    name: 'Greece',
    value: 'Greece',
    flag: '\ud83c\uddec\ud83c\uddf7',
    countryCode: 'GR',
  },
  {
    name: 'Grenada',
    value: 'Grenada',
    flag: '\ud83c\uddec\ud83c\udde9',
    countryCode: 'GD',
  },
  {
    name: 'Greenland',
    value: 'Greenland',
    flag: '\ud83c\uddec\ud83c\uddf1',
    countryCode: 'GL',
  },
  {
    name: 'Guatemala',
    value: 'Guatemala',
    flag: '\ud83c\uddec\ud83c\uddf9',
    countryCode: 'GT',
  },
  {
    name: 'French Guiana',
    value: 'French Guiana',
    flag: '\ud83c\uddec\ud83c\uddeb',
    countryCode: 'GF',
  },
  {
    name: 'Guam',
    value: 'Guam',
    flag: '\ud83c\uddec\ud83c\uddfa',
    countryCode: 'GU',
  },
  {
    name: 'Guyana',
    value: 'Guyana',
    flag: '\ud83c\uddec\ud83c\uddfe',
    countryCode: 'GY',
  },
  {
    name: 'Hong Kong',
    value: 'Hong Kong',
    flag: '\ud83c\udded\ud83c\uddf0',
    countryCode: 'HK',
  },
  {
    name: 'Heard Island and McDonald Islands',
    value: 'Heard Island and McDonald Islands',
    flag: '\ud83c\udded\ud83c\uddf2',
    countryCode: 'HM',
  },
  {
    name: 'Honduras',
    value: 'Honduras',
    flag: '\ud83c\udded\ud83c\uddf3',
    countryCode: 'HN',
  },
  {
    name: 'Croatia',
    value: 'Croatia',
    flag: '\ud83c\udded\ud83c\uddf7',
    countryCode: 'HR',
  },
  {
    name: 'Haiti',
    value: 'Haiti',
    flag: '\ud83c\udded\ud83c\uddf9',
    countryCode: 'HT',
  },
  {
    name: 'Hungary',
    value: 'Hungary',
    flag: '\ud83c\udded\ud83c\uddfa',
    countryCode: 'HU',
  },
  {
    name: 'Indonesia',
    value: 'Indonesia',
    flag: '\ud83c\uddee\ud83c\udde9',
    countryCode: 'ID',
  },
  {
    name: 'Isle of Man',
    value: 'Isle of Man',
    flag: '\ud83c\uddee\ud83c\uddf2',
    countryCode: 'IM',
  },
  {
    name: 'India',
    value: 'India',
    flag: '\ud83c\uddee\ud83c\uddf3',
    countryCode: 'IN',
  },
  {
    name: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
    flag: '\ud83c\uddee\ud83c\uddf4',
    countryCode: 'IO',
  },
  {
    name: 'Ireland',
    value: 'Ireland',
    flag: '\ud83c\uddee\ud83c\uddea',
    countryCode: 'IE',
  },
  {
    name: 'Iran, Islamic Republic of',
    value: 'Iran, Islamic Republic of',
    flag: '\ud83c\uddee\ud83c\uddf7',
    countryCode: 'IR',
  },
  {
    name: 'Iraq',
    value: 'Iraq',
    flag: '\ud83c\uddee\ud83c\uddf6',
    countryCode: 'IQ',
  },
  {
    name: 'Iceland',
    value: 'Iceland',
    flag: '\ud83c\uddee\ud83c\uddf8',
    countryCode: 'IS',
  },
  {
    name: 'Israel',
    value: 'Israel',
    flag: '\ud83c\uddee\ud83c\uddf1',
    countryCode: 'IL',
  },
  {
    name: 'Italy',
    value: 'Italy',
    flag: '\ud83c\uddee\ud83c\uddf9',
    countryCode: 'IT',
  },
  {
    name: 'Jamaica',
    value: 'Jamaica',
    flag: '\ud83c\uddef\ud83c\uddf2',
    countryCode: 'JM',
  },
  {
    name: 'Jersey',
    value: 'Jersey',
    flag: '\ud83c\uddef\ud83c\uddea',
    countryCode: 'JE',
  },
  {
    name: 'Jordan',
    value: 'Jordan',
    flag: '\ud83c\uddef\ud83c\uddf4',
    countryCode: 'JO',
  },
  {
    name: 'Japan',
    value: 'Japan',
    flag: '\ud83c\uddef\ud83c\uddf5',
    countryCode: 'JP',
  },
  {
    name: 'Kazakhstan',
    value: 'Kazakhstan',
    flag: '\ud83c\uddf0\ud83c\uddff',
    countryCode: 'KZ',
  },
  {
    name: 'Kenya',
    value: 'Kenya',
    flag: '\ud83c\uddf0\ud83c\uddea',
    countryCode: 'KE',
  },
  {
    name: 'Kyrgyzstan',
    value: 'Kyrgyzstan',
    flag: '\ud83c\uddf0\ud83c\uddec',
    countryCode: 'KG',
  },
  {
    name: 'Cambodia',
    value: 'Cambodia',
    flag: '\ud83c\uddf0\ud83c\udded',
    countryCode: 'KH',
  },
  {
    name: 'Kiribati',
    value: 'Kiribati',
    flag: '\ud83c\uddf0\ud83c\uddee',
    countryCode: 'KI',
  },
  {
    name: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
    flag: '\ud83c\uddf0\ud83c\uddf3',
    countryCode: 'KN',
  },
  {
    name: 'Korea, Republic of',
    value: 'Korea, Republic of',
    flag: '\ud83c\uddf0\ud83c\uddf7',
    countryCode: 'KR',
  },
  {
    name: 'Kuwait',
    value: 'Kuwait',
    flag: '\ud83c\uddf0\ud83c\uddfc',
    countryCode: 'KW',
  },
  {
    name: "Lao People's Democratic Republic",
    value: "Lao People's Democratic Republic",
    flag: '\ud83c\uddf1\ud83c\udde6',
    countryCode: 'LA',
  },
  {
    name: 'Lebanon',
    value: 'Lebanon',
    flag: '\ud83c\uddf1\ud83c\udde7',
    countryCode: 'LB',
  },
  {
    name: 'Liberia',
    value: 'Liberia',
    flag: '\ud83c\uddf1\ud83c\uddf7',
    countryCode: 'LR',
  },
  {
    name: 'Libya',
    value: 'Libya',
    flag: '\ud83c\uddf1\ud83c\uddfe',
    countryCode: 'LY',
  },
  {
    name: 'Saint Lucia',
    value: 'Saint Lucia',
    flag: '\ud83c\uddf1\ud83c\udde8',
    countryCode: 'LC',
  },
  {
    name: 'Liechtenstein',
    value: 'Liechtenstein',
    flag: '\ud83c\uddf1\ud83c\uddee',
    countryCode: 'LI',
  },
  {
    name: 'Sri Lanka',
    value: 'Sri Lanka',
    flag: '\ud83c\uddf1\ud83c\uddf0',
    countryCode: 'LK',
  },
  {
    name: 'Lesotho',
    value: 'Lesotho',
    flag: '\ud83c\uddf1\ud83c\uddf8',
    countryCode: 'LS',
  },
  {
    name: 'Lithuania',
    value: 'Lithuania',
    flag: '\ud83c\uddf1\ud83c\uddf9',
    countryCode: 'LT',
  },
  {
    name: 'Luxembourg',
    value: 'Luxembourg',
    flag: '\ud83c\uddf1\ud83c\uddfa',
    countryCode: 'LU',
  },
  {
    name: 'Latvia',
    value: 'Latvia',
    flag: '\ud83c\uddf1\ud83c\uddfb',
    countryCode: 'LV',
  },
  {
    name: 'Macao',
    value: 'Macao',
    flag: '\ud83c\uddf2\ud83c\uddf4',
    countryCode: 'MO',
  },
  {
    name: 'Saint Martin (French part)',
    value: 'Saint Martin (French part)',
    flag: '\ud83c\uddf2\ud83c\uddeb',
    countryCode: 'MF',
  },
  {
    name: 'Morocco',
    value: 'Morocco',
    flag: '\ud83c\uddf2\ud83c\udde6',
    countryCode: 'MA',
  },
  {
    name: 'Monaco',
    value: 'Monaco',
    flag: '\ud83c\uddf2\ud83c\udde8',
    countryCode: 'MC',
  },
  {
    name: 'Moldova, Republic of',
    value: 'Moldova, Republic of',
    flag: '\ud83c\uddf2\ud83c\udde9',
    countryCode: 'MD',
  },
  {
    name: 'Madagascar',
    value: 'Madagascar',
    flag: '\ud83c\uddf2\ud83c\uddec',
    countryCode: 'MG',
  },
  {
    name: 'Maldives',
    value: 'Maldives',
    flag: '\ud83c\uddf2\ud83c\uddfb',
    countryCode: 'MV',
  },
  {
    name: 'Mexico',
    value: 'Mexico',
    flag: '\ud83c\uddf2\ud83c\uddfd',
    countryCode: 'MX',
  },
  {
    name: 'Marshall Islands',
    value: 'Marshall Islands',
    flag: '\ud83c\uddf2\ud83c\udded',
    countryCode: 'MH',
  },
  {
    name: 'North Macedonia',
    value: 'North Macedonia',
    flag: '\ud83c\uddf2\ud83c\uddf0',
    countryCode: 'MK',
  },
  {
    name: 'Mali',
    value: 'Mali',
    flag: '\ud83c\uddf2\ud83c\uddf1',
    countryCode: 'ML',
  },
  {
    name: 'Malta',
    value: 'Malta',
    flag: '\ud83c\uddf2\ud83c\uddf9',
    countryCode: 'MT',
  },
  {
    name: 'Myanmar',
    value: 'Myanmar',
    flag: '\ud83c\uddf2\ud83c\uddf2',
    countryCode: 'MM',
  },
  {
    name: 'Montenegro',
    value: 'Montenegro',
    flag: '\ud83c\uddf2\ud83c\uddea',
    countryCode: 'ME',
  },
  {
    name: 'Mongolia',
    value: 'Mongolia',
    flag: '\ud83c\uddf2\ud83c\uddf3',
    countryCode: 'MN',
  },
  {
    name: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
    flag: '\ud83c\uddf2\ud83c\uddf5',
    countryCode: 'MP',
  },
  {
    name: 'Mozambique',
    value: 'Mozambique',
    flag: '\ud83c\uddf2\ud83c\uddff',
    countryCode: 'MZ',
  },
  {
    name: 'Mauritania',
    value: 'Mauritania',
    flag: '\ud83c\uddf2\ud83c\uddf7',
    countryCode: 'MR',
  },
  {
    name: 'Montserrat',
    value: 'Montserrat',
    flag: '\ud83c\uddf2\ud83c\uddf8',
    countryCode: 'MS',
  },
  {
    name: 'Martinique',
    value: 'Martinique',
    flag: '\ud83c\uddf2\ud83c\uddf6',
    countryCode: 'MQ',
  },
  {
    name: 'Mauritius',
    value: 'Mauritius',
    flag: '\ud83c\uddf2\ud83c\uddfa',
    countryCode: 'MU',
  },
  {
    name: 'Malawi',
    value: 'Malawi',
    flag: '\ud83c\uddf2\ud83c\uddfc',
    countryCode: 'MW',
  },
  {
    name: 'Malaysia',
    value: 'Malaysia',
    flag: '\ud83c\uddf2\ud83c\uddfe',
    countryCode: 'MY',
  },
  {
    name: 'Mayotte',
    value: 'Mayotte',
    flag: '\ud83c\uddfe\ud83c\uddf9',
    countryCode: 'YT',
  },
  {
    name: 'Namibia',
    value: 'Namibia',
    flag: '\ud83c\uddf3\ud83c\udde6',
    countryCode: 'NA',
  },
  {
    name: 'New Caledonia',
    value: 'New Caledonia',
    flag: '\ud83c\uddf3\ud83c\udde8',
    countryCode: 'NC',
  },
  {
    name: 'Niger',
    value: 'Niger',
    flag: '\ud83c\uddf3\ud83c\uddea',
    countryCode: 'NE',
  },
  {
    name: 'Norfolk Island',
    value: 'Norfolk Island',
    flag: '\ud83c\uddf3\ud83c\uddeb',
    countryCode: 'NF',
  },
  {
    name: 'Nigeria',
    value: 'Nigeria',
    flag: '\ud83c\uddf3\ud83c\uddec',
    countryCode: 'NG',
  },
  {
    name: 'Nicaragua',
    value: 'Nicaragua',
    flag: '\ud83c\uddf3\ud83c\uddee',
    countryCode: 'NI',
  },
  {
    name: 'Niue',
    value: 'Niue',
    flag: '\ud83c\uddf3\ud83c\uddfa',
    countryCode: 'NU',
  },
  {
    name: 'Netherlands',
    value: 'Netherlands',
    flag: '\ud83c\uddf3\ud83c\uddf1',
    countryCode: 'NL',
  },
  {
    name: 'Norway',
    value: 'Norway',
    flag: '\ud83c\uddf3\ud83c\uddf4',
    countryCode: 'NO',
  },
  {
    name: 'Nepal',
    value: 'Nepal',
    flag: '\ud83c\uddf3\ud83c\uddf5',
    countryCode: 'NP',
  },
  {
    name: 'Nauru',
    value: 'Nauru',
    flag: '\ud83c\uddf3\ud83c\uddf7',
    countryCode: 'NR',
  },
  {
    name: 'New Zealand',
    value: 'New Zealand',
    flag: '\ud83c\uddf3\ud83c\uddff',
    countryCode: 'NZ',
  },
  {
    name: 'Oman',
    value: 'Oman',
    flag: '\ud83c\uddf4\ud83c\uddf2',
    countryCode: 'OM',
  },
  {
    name: 'Pakistan',
    value: 'Pakistan',
    flag: '\ud83c\uddf5\ud83c\uddf0',
    countryCode: 'PK',
  },
  {
    name: 'Panama',
    value: 'Panama',
    flag: '\ud83c\uddf5\ud83c\udde6',
    countryCode: 'PA',
  },
  {
    name: 'Pitcairn',
    value: 'Pitcairn',
    flag: '\ud83c\uddf5\ud83c\uddf3',
    countryCode: 'PN',
  },
  {
    name: 'Peru',
    value: 'Peru',
    flag: '\ud83c\uddf5\ud83c\uddea',
    countryCode: 'PE',
  },
  {
    name: 'Philippines',
    value: 'Philippines',
    flag: '\ud83c\uddf5\ud83c\udded',
    countryCode: 'PH',
  },
  {
    name: 'Palau',
    value: 'Palau',
    flag: '\ud83c\uddf5\ud83c\uddfc',
    countryCode: 'PW',
  },
  {
    name: 'Papua New Guinea',
    value: 'Papua New Guinea',
    flag: '\ud83c\uddf5\ud83c\uddec',
    countryCode: 'PG',
  },
  {
    name: 'Poland',
    value: 'Poland',
    flag: '\ud83c\uddf5\ud83c\uddf1',
    countryCode: 'PL',
  },
  {
    name: 'Puerto Rico',
    value: 'Puerto Rico',
    flag: '\ud83c\uddf5\ud83c\uddf7',
    countryCode: 'PR',
  },
  {
    name: "Korea, Democratic People's Republic of",
    value: "Korea, Democratic People's Republic of",
    flag: '\ud83c\uddf0\ud83c\uddf5',
    countryCode: 'KP',
  },
  {
    name: 'Portugal',
    value: 'Portugal',
    flag: '\ud83c\uddf5\ud83c\uddf9',
    countryCode: 'PT',
  },
  {
    name: 'Paraguay',
    value: 'Paraguay',
    flag: '\ud83c\uddf5\ud83c\uddfe',
    countryCode: 'PY',
  },
  {
    name: 'Palestine, State of',
    value: 'Palestine, State of',
    flag: '\ud83c\uddf5\ud83c\uddf8',
    countryCode: 'PS',
  },
  {
    name: 'French Polynesia',
    value: 'French Polynesia',
    flag: '\ud83c\uddf5\ud83c\uddeb',
    countryCode: 'PF',
  },
  {
    name: 'Qatar',
    value: 'Qatar',
    flag: '\ud83c\uddf6\ud83c\udde6',
    countryCode: 'QA',
  },
  {
    name: 'R\u00e9union',
    value: 'R\u00e9union',
    flag: '\ud83c\uddf7\ud83c\uddea',
    countryCode: 'RE',
  },
  {
    name: 'Romania',
    value: 'Romania',
    flag: '\ud83c\uddf7\ud83c\uddf4',
    countryCode: 'RO',
  },
  {
    name: 'Russian Federation',
    value: 'Russian Federation',
    flag: '\ud83c\uddf7\ud83c\uddfa',
    countryCode: 'RU',
  },
  {
    name: 'Rwanda',
    value: 'Rwanda',
    flag: '\ud83c\uddf7\ud83c\uddfc',
    countryCode: 'RW',
  },
  {
    name: 'Saudi Arabia',
    value: 'Saudi Arabia',
    flag: '\ud83c\uddf8\ud83c\udde6',
    countryCode: 'SA',
  },
  {
    name: 'Sudan',
    value: 'Sudan',
    flag: '\ud83c\uddf8\ud83c\udde9',
    countryCode: 'SD',
  },
  {
    name: 'Senegal',
    value: 'Senegal',
    flag: '\ud83c\uddf8\ud83c\uddf3',
    countryCode: 'SN',
  },
  {
    name: 'Singapore',
    value: 'Singapore',
    flag: '\ud83c\uddf8\ud83c\uddec',
    countryCode: 'SG',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
    flag: '\ud83c\uddec\ud83c\uddf8',
    countryCode: 'GS',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    value: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: '\ud83c\uddf8\ud83c\udded',
    countryCode: 'SH',
  },
  {
    name: 'Svalbard and Jan Mayen',
    value: 'Svalbard and Jan Mayen',
    flag: '\ud83c\uddf8\ud83c\uddef',
    countryCode: 'SJ',
  },
  {
    name: 'Solomon Islands',
    value: 'Solomon Islands',
    flag: '\ud83c\uddf8\ud83c\udde7',
    countryCode: 'SB',
  },
  {
    name: 'Sierra Leone',
    value: 'Sierra Leone',
    flag: '\ud83c\uddf8\ud83c\uddf1',
    countryCode: 'SL',
  },
  {
    name: 'El Salvador',
    value: 'El Salvador',
    flag: '\ud83c\uddf8\ud83c\uddfb',
    countryCode: 'SV',
  },
  {
    name: 'San Marino',
    value: 'San Marino',
    flag: '\ud83c\uddf8\ud83c\uddf2',
    countryCode: 'SM',
  },
  {
    name: 'Somalia',
    value: 'Somalia',
    flag: '\ud83c\uddf8\ud83c\uddf4',
    countryCode: 'SO',
  },
  {
    name: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
    flag: '\ud83c\uddf5\ud83c\uddf2',
    countryCode: 'PM',
  },
  {
    name: 'Serbia',
    value: 'Serbia',
    flag: '\ud83c\uddf7\ud83c\uddf8',
    countryCode: 'RS',
  },
  {
    name: 'South Sudan',
    value: 'South Sudan',
    flag: '\ud83c\uddf8\ud83c\uddf8',
    countryCode: 'SS',
  },
  {
    name: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
    flag: '\ud83c\uddf8\ud83c\uddf9',
    countryCode: 'ST',
  },
  {
    name: 'Suriname',
    value: 'Suriname',
    flag: '\ud83c\uddf8\ud83c\uddf7',
    countryCode: 'SR',
  },
  {
    name: 'Slovakia',
    value: 'Slovakia',
    flag: '\ud83c\uddf8\ud83c\uddf0',
    countryCode: 'SK',
  },
  {
    name: 'Slovenia',
    value: 'Slovenia',
    flag: '\ud83c\uddf8\ud83c\uddee',
    countryCode: 'SI',
  },
  {
    name: 'Sweden',
    value: 'Sweden',
    flag: '\ud83c\uddf8\ud83c\uddea',
    countryCode: 'SE',
  },
  {
    name: 'Eswatini',
    value: 'Eswatini',
    flag: '\ud83c\uddf8\ud83c\uddff',
    countryCode: 'SZ',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    value: 'Sint Maarten (Dutch part)',
    flag: '\ud83c\uddf8\ud83c\uddfd',
    countryCode: 'SX',
  },
  {
    name: 'Seychelles',
    value: 'Seychelles',
    flag: '\ud83c\uddf8\ud83c\udde8',
    countryCode: 'SC',
  },
  {
    name: 'Syrian Arab Republic',
    value: 'Syrian Arab Republic',
    flag: '\ud83c\uddf8\ud83c\uddfe',
    countryCode: 'SY',
  },
  {
    name: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
    flag: '\ud83c\uddf9\ud83c\udde8',
    countryCode: 'TC',
  },
  {
    name: 'Chad',
    value: 'Chad',
    flag: '\ud83c\uddf9\ud83c\udde9',
    countryCode: 'TD',
  },
  {
    name: 'Togo',
    value: 'Togo',
    flag: '\ud83c\uddf9\ud83c\uddec',
    countryCode: 'TG',
  },
  {
    name: 'Thailand',
    value: 'Thailand',
    flag: '\ud83c\uddf9\ud83c\udded',
    countryCode: 'TH',
  },
  {
    name: 'Tajikistan',
    value: 'Tajikistan',
    flag: '\ud83c\uddf9\ud83c\uddef',
    countryCode: 'TJ',
  },
  {
    name: 'Tokelau',
    value: 'Tokelau',
    flag: '\ud83c\uddf9\ud83c\uddf0',
    countryCode: 'TK',
  },
  {
    name: 'Turkmenistan',
    value: 'Turkmenistan',
    flag: '\ud83c\uddf9\ud83c\uddf2',
    countryCode: 'TM',
  },
  {
    name: 'Timor-Leste',
    value: 'Timor-Leste',
    flag: '\ud83c\uddf9\ud83c\uddf1',
    countryCode: 'TL',
  },
  {
    name: 'Tonga',
    value: 'Tonga',
    flag: '\ud83c\uddf9\ud83c\uddf4',
    countryCode: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    value: 'Trinidad and Tobago',
    flag: '\ud83c\uddf9\ud83c\uddf9',
    countryCode: 'TT',
  },
  {
    name: 'Tunisia',
    value: 'Tunisia',
    flag: '\ud83c\uddf9\ud83c\uddf3',
    countryCode: 'TN',
  },
  {
    name: 'Turkey',
    value: 'Turkey',
    flag: '\ud83c\uddf9\ud83c\uddf7',
    countryCode: 'TR',
  },
  {
    name: 'Tuvalu',
    value: 'Tuvalu',
    flag: '\ud83c\uddf9\ud83c\uddfb',
    countryCode: 'TV',
  },
  {
    name: 'Taiwan, Province of China',
    value: 'Taiwan, Province of China',
    flag: '\ud83c\uddf9\ud83c\uddfc',
    countryCode: 'TW',
  },
  {
    name: 'Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
    flag: '\ud83c\uddf9\ud83c\uddff',
    countryCode: 'TZ',
  },
  {
    name: 'Uganda',
    value: 'Uganda',
    flag: '\ud83c\uddfa\ud83c\uddec',
    countryCode: 'UG',
  },
  {
    name: 'Ukraine',
    value: 'Ukraine',
    flag: '\ud83c\uddfa\ud83c\udde6',
    countryCode: 'UA',
  },
  {
    name: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
    flag: '\ud83c\uddfa\ud83c\uddf2',
    countryCode: 'UM',
  },
  {
    name: 'Uruguay',
    value: 'Uruguay',
    flag: '\ud83c\uddfa\ud83c\uddfe',
    countryCode: 'UY',
  },
  {
    name: 'United States',
    value: 'United States',
    flag: '\ud83c\uddfa\ud83c\uddf8',
    countryCode: 'US',
  },
  {
    name: 'Uzbekistan',
    value: 'Uzbekistan',
    flag: '\ud83c\uddfa\ud83c\uddff',
    countryCode: 'UZ',
  },
  {
    name: 'Holy See (Vatican City State)',
    value: 'Holy See (Vatican City State)',
    flag: '\ud83c\uddfb\ud83c\udde6',
    countryCode: 'VA',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
    flag: '\ud83c\uddfb\ud83c\udde8',
    countryCode: 'VC',
  },
  {
    name: 'Venezuela, Bolivarian Republic of',
    value: 'Venezuela, Bolivarian Republic of',
    flag: '\ud83c\uddfb\ud83c\uddea',
    countryCode: 'VE',
  },
  {
    name: 'Virgin Islands, British',
    value: 'Virgin Islands, British',
    flag: '\ud83c\uddfb\ud83c\uddec',
    countryCode: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    value: 'Virgin Islands, U.S.',
    flag: '\ud83c\uddfb\ud83c\uddee',
    countryCode: 'VI',
  },
  {
    name: 'Viet Nam',
    value: 'Viet Nam',
    flag: '\ud83c\uddfb\ud83c\uddf3',
    countryCode: 'VN',
  },
  {
    name: 'Vanuatu',
    value: 'Vanuatu',
    flag: '\ud83c\uddfb\ud83c\uddfa',
    countryCode: 'VU',
  },
  {
    name: 'Wallis and Futuna',
    value: 'Wallis and Futuna',
    flag: '\ud83c\uddfc\ud83c\uddeb',
    countryCode: 'WF',
  },
  {
    name: 'Samoa',
    value: 'Samoa',
    flag: '\ud83c\uddfc\ud83c\uddf8',
    countryCode: 'WS',
  },
  {
    name: 'Yemen',
    value: 'Yemen',
    flag: '\ud83c\uddfe\ud83c\uddea',
    countryCode: 'YE',
  },
  {
    name: 'South Africa',
    value: 'South Africa',
    flag: '\ud83c\uddff\ud83c\udde6',
    countryCode: 'ZA',
  },
  {
    name: 'Zambia',
    value: 'Zambia',
    flag: '\ud83c\uddff\ud83c\uddf2',
    countryCode: 'ZM',
  },
  {
    name: 'Zimbabwe',
    value: 'Zimbabwe',
    flag: '\ud83c\uddff\ud83c\uddfc',
    countryCode: 'ZW',
  },
];
